#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ProjectEF Wwise Audio Logic Tester GUI."""
from __future__ import annotations

import json
import queue
import re
import sys
import threading
import tkinter as tk
from datetime import datetime
from pathlib import Path
from tkinter import filedialog, messagebox, simpledialog, ttk
from tkinter.scrolledtext import ScrolledText

sys.path.insert(0, str(Path(__file__).resolve().parent))
from audio_logic_engine import (  # noqa: E402
    DEFAULT_WAAPI_URL,
    AudioLogicEngine,
    run_plan,
    validate_plan,
)
from audio_logic_llm import LLMConfig, generate_plan, route_label  # noqa: E402

APP_DIR = Path(__file__).resolve().parent
SCENARIO_DIR = APP_DIR / "audio_logic_scenarios"
RAW_DIR = SCENARIO_DIR / "raw"
REPORT_DIR = APP_DIR.parent / "Reports"

BG = "#0f1722"
PANEL = "#151f2d"
PANEL_2 = "#1b2636"
CARD = "#202c3d"
CARD_HOVER = "#26364b"
INK = "#edf4ff"
MUTED = "#9fb0c6"
LINE = "#334258"
ACCENT = "#4db6ff"
GOOD = "#55d68a"
BAD = "#ff6b6b"
WARN = "#ffcc66"

EXAMPLE = """1 Post Play_Stamina
2 缓慢Set RTPC_Player_Stamina 从50到0，大概用时15s
3 到0时post Play_Gasp
4 快速Set RTPC_Player_Stamina 从0到50，大概用时1s
5 超过40时Post Play_Recover
6 男女各自测试完整流程"""


class AudioLogicTesterGUI(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("ProjectEF Wwise Audio Logic Tester")
        self.geometry("1240x820")
        self.minsize(1100, 720)
        self.configure(bg=BG)

        self.q: queue.Queue[tuple[str, object]] = queue.Queue()
        self.objects: dict[str, object] | None = None
        self.stop_flag = threading.Event()
        self.run_thread: threading.Thread | None = None

        self.url_var = tk.StringVar(value=DEFAULT_WAAPI_URL)
        self.mode_var = tk.StringVar(value="auto")
        self.provider_var = tk.StringVar(value="ollama")
        self.model_var = tk.StringVar(value="qwen2.5:7b-instruct")
        self.conn_var = tk.StringVar(value="Not checked")
        self.connect_detail_var = tk.StringVar(value="Click Connect to check WAAPI.")
        self.object_var = tk.StringVar(value="Connect to scan")
        self.source_var = tk.StringVar(value="Generated by: manual")
        self.run_state_var = tk.StringVar(value="Idle")
        self.route_var = tk.StringVar(value="")
        self.status_var = tk.StringVar(value="Ready")
        self.run_name_var = tk.StringVar(value="No DSL loaded")
        self.lib_var = tk.StringVar()

        self.configure_style()
        self.build_ui()
        self.refresh_route_preview()
        self.refresh_library()
        self.after(100, self.drain_queue)

    # ---------- UI ----------
    def configure_style(self) -> None:
        style = ttk.Style(self)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass
        style.configure("TFrame", background=BG)
        style.configure("TLabel", background=BG, foreground=INK)
        style.configure("TButton", padding=(10, 6))
        style.configure("TCombobox", fieldbackground=PANEL_2, background=PANEL_2, foreground=INK)
        style.configure("Treeview", background="#101720", fieldbackground="#101720", foreground=INK, rowheight=24)
        style.map("Treeview", background=[("selected", "#315577")], foreground=[("selected", "#ffffff")])

    def build_ui(self) -> None:
        root = tk.Frame(self, bg=BG)
        root.pack(fill=tk.BOTH, expand=True)

        header = tk.Frame(root, bg=BG)
        header.pack(fill=tk.X, padx=18, pady=(16, 10))
        title_block = tk.Frame(header, bg=BG)
        title_block.pack(side=tk.LEFT, fill=tk.X, expand=True)
        tk.Label(
            title_block,
            text="ProjectEF Wwise Audio Logic Tester",
            bg=BG,
            fg=INK,
            font=("Segoe UI", 22, "bold"),
        ).pack(anchor="w")
        tk.Label(
            title_block,
            text="Natural language to WAAPI playback checks",
            bg=BG,
            fg=MUTED,
            font=("Segoe UI", 10),
        ).pack(anchor="w", pady=(2, 0))

        stats = tk.Frame(root, bg=BG)
        stats.pack(fill=tk.X, padx=18, pady=(0, 12))
        self.metric(stats, "WAAPI", self.conn_var, width=210).pack(side=tk.LEFT, padx=(0, 8))
        self.metric(stats, "Objects", self.object_var).pack(side=tk.LEFT, padx=(0, 8))
        self.metric(stats, "DSL Source", self.source_var, width=360).pack(side=tk.LEFT, padx=(0, 8))
        self.metric(stats, "Run", self.run_state_var, width=150).pack(side=tk.LEFT)

        config = self.panel(root)
        config.pack(fill=tk.X, padx=18, pady=(0, 12))
        self.entry(config, "WAAPI URL", self.url_var, 270).pack(side=tk.LEFT, padx=(12, 10), pady=10)
        self.connect_button = self.button(config, "Connect", self.do_connect, ACCENT, "#06111d")
        self.connect_button.pack(side=tk.LEFT, padx=(0, 10), pady=10)
        self.connect_detail_label = tk.Label(
            config,
            textvariable=self.connect_detail_var,
            bg=PANEL_2,
            fg=INK,
            font=("Segoe UI", 9, "bold"),
            anchor="w",
            width=30,
            padx=10,
        )
        self.connect_detail_label.pack(side=tk.LEFT, padx=(0, 12), pady=10, ipady=8)

        self.combo(config, "Mode", self.mode_var, ["auto", "local", "remote"], 82).pack(
            side=tk.LEFT, padx=(0, 10), pady=10
        )
        provider = self.combo(
            config,
            "Provider",
            self.provider_var,
            ["ollama", "openai", "anthropic", "claude-cli", "codex-cli", "codex"],
            118,
        )
        provider.pack(side=tk.LEFT, padx=(0, 10), pady=10)
        self.entry(config, "Model / command", self.model_var, 190).pack(side=tk.LEFT, padx=(0, 10), pady=10)
        self.provider_var.trace_add("write", lambda *_args: self.on_provider_changed())
        self.mode_var.trace_add("write", lambda *_args: self.refresh_route_preview())
        self.model_var.trace_add("write", lambda *_args: self.refresh_route_preview())

        tk.Label(config, textvariable=self.route_var, bg=PANEL, fg=MUTED, font=("Segoe UI", 9)).pack(
            side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 12), pady=10
        )

        actions = self.panel(root)
        actions.pack(fill=tk.X, padx=18, pady=(0, 12))
        self.button(actions, "Generate DSL", self.do_generate, ACCENT, "#06111d").pack(
            side=tk.LEFT, padx=(12, 8), pady=10
        )
        self.button(actions, "Run", self.do_run, GOOD, "#06120f").pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(actions, "Stop", self.do_stop, CARD, INK).pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(actions, "Save Raw", self.do_save_raw_description, CARD, INK).pack(
            side=tk.LEFT, padx=(0, 8), pady=10
        )
        self.button(actions, "Save Bundle", self.do_save_bundle, CARD, INK).pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(actions, "Load", self.do_load, CARD, INK).pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(actions, "Stamina Preset", self.do_stamina_preset, CARD, INK).pack(
            side=tk.LEFT, padx=(0, 12), pady=10
        )
        tk.Label(actions, textvariable=self.run_name_var, bg=PANEL, fg=MUTED, font=("Segoe UI", 9)).pack(
            side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 12)
        )

        library = self.panel(root)
        library.pack(fill=tk.X, padx=18, pady=(0, 12))
        tk.Label(library, text="Scenario Library", bg=PANEL, fg=MUTED, font=("Segoe UI", 10, "bold")).pack(
            side=tk.LEFT, padx=(12, 8), pady=10
        )
        self.lib_combo = ttk.Combobox(library, textvariable=self.lib_var, width=38, state="readonly")
        self.lib_combo.pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(library, "Load Selected", self.do_lib_load, CARD, INK).pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(library, "Save To Library", self.do_lib_save, CARD, INK).pack(side=tk.LEFT, padx=(0, 8), pady=10)
        self.button(library, "Refresh", self.refresh_library, CARD, INK).pack(side=tk.LEFT, padx=(0, 12), pady=10)

        body = tk.PanedWindow(root, orient=tk.VERTICAL, bg=BG, sashwidth=7, bd=0)
        body.pack(fill=tk.BOTH, expand=True, padx=18, pady=(0, 12))
        top = tk.PanedWindow(body, orient=tk.HORIZONTAL, bg=BG, sashwidth=7, bd=0)
        body.add(top, stretch="always", minsize=420)

        left = self.panel(top)
        right = self.panel(top)
        top.add(left, stretch="always", minsize=460)
        top.add(right, stretch="always", minsize=460)

        tk.Label(left, text="Original Description", bg=PANEL, fg=MUTED, font=("Segoe UI", 10, "bold")).pack(
            anchor="w", padx=12, pady=(10, 6)
        )
        self.scenario = ScrolledText(
            left,
            height=14,
            wrap=tk.WORD,
            bg="#101720",
            fg=INK,
            insertbackground=INK,
            relief=tk.FLAT,
            font=("Microsoft YaHei UI", 10),
            padx=10,
            pady=8,
        )
        self.scenario.pack(fill=tk.BOTH, expand=True, padx=12, pady=(0, 12))
        self.scenario.insert("1.0", EXAMPLE)

        tk.Label(right, text="Test DSL", bg=PANEL, fg=MUTED, font=("Segoe UI", 10, "bold")).pack(
            anchor="w", padx=12, pady=(10, 6)
        )
        self.dsl_text = ScrolledText(
            right,
            height=14,
            wrap=tk.NONE,
            bg="#101720",
            fg="#dbeafe",
            insertbackground=INK,
            relief=tk.FLAT,
            font=("Consolas", 10),
            padx=10,
            pady=8,
        )
        self.dsl_text.pack(fill=tk.BOTH, expand=True, padx=12, pady=(0, 12))
        self.dsl_text.bind("<KeyRelease>", lambda _event: self.sync_name_from_dsl())

        log_panel = self.panel(body)
        body.add(log_panel, stretch="always", minsize=190)
        log_header = tk.Frame(log_panel, bg=PANEL)
        log_header.pack(fill=tk.X, padx=12, pady=(10, 6))
        tk.Label(log_header, text="Run Log", bg=PANEL, fg=MUTED, font=("Segoe UI", 10, "bold")).pack(side=tk.LEFT)
        self.button(log_header, "Clear", self.clear_log, CARD, INK).pack(side=tk.RIGHT)
        self.log_text = ScrolledText(
            log_panel,
            height=9,
            wrap=tk.WORD,
            state=tk.DISABLED,
            bg="#101720",
            fg="#dbeafe",
            insertbackground=INK,
            relief=tk.FLAT,
            font=("Consolas", 10),
            padx=10,
            pady=8,
        )
        self.log_text.pack(fill=tk.BOTH, expand=True, padx=12, pady=(0, 12))

        footer = tk.Frame(root, bg=BG)
        footer.pack(fill=tk.X, padx=18, pady=(0, 12))
        tk.Label(footer, textvariable=self.status_var, bg=BG, fg=MUTED, font=("Segoe UI", 9)).pack(side=tk.LEFT)
        tk.Label(footer, text=str(APP_DIR), bg=BG, fg="#65748a", font=("Segoe UI", 9)).pack(side=tk.RIGHT)

    def panel(self, parent: tk.Misc) -> tk.Frame:
        return tk.Frame(parent, bg=PANEL, highlightbackground=LINE, highlightthickness=1)

    def metric(self, parent: tk.Misc, label: str, variable: tk.StringVar, width: int = 150) -> tk.Frame:
        box = tk.Frame(parent, bg=PANEL, highlightbackground=LINE, highlightthickness=1, width=width, height=52)
        box.pack_propagate(False)
        tk.Label(box, text=label, bg=PANEL, fg=MUTED, font=("Segoe UI", 8, "bold")).pack(
            anchor="w", padx=10, pady=(6, 0)
        )
        tk.Label(box, textvariable=variable, bg=PANEL, fg=INK, font=("Segoe UI", 10, "bold")).pack(
            anchor="w", padx=10, pady=(0, 6)
        )
        return box

    def button(self, parent: tk.Misc, text: str, command, bg: str = CARD, fg: str = INK) -> tk.Button:
        return tk.Button(
            parent,
            text=text,
            command=command,
            bg=bg,
            fg=fg,
            activebackground="#82ccff" if bg == ACCENT else CARD_HOVER,
            activeforeground=fg,
            relief=tk.FLAT,
            padx=14,
            pady=7,
            font=("Segoe UI", 9, "bold" if bg in {ACCENT, GOOD} else "normal"),
        )

    def entry(self, parent: tk.Misc, label: str, variable: tk.StringVar, width_px: int) -> tk.Frame:
        frame = tk.Frame(parent, bg=PANEL)
        tk.Label(frame, text=label, bg=PANEL, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w")
        tk.Entry(
            frame,
            textvariable=variable,
            bg=PANEL_2,
            fg=INK,
            insertbackground=INK,
            relief=tk.FLAT,
            font=("Segoe UI", 10),
            width=max(8, width_px // 9),
        ).pack(anchor="w", ipady=5, pady=(2, 0))
        return frame

    def combo(
        self,
        parent: tk.Misc,
        label: str,
        variable: tk.StringVar,
        values: list[str],
        width_px: int,
    ) -> tk.Frame:
        frame = tk.Frame(parent, bg=PANEL)
        tk.Label(frame, text=label, bg=PANEL, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w")
        ttk.Combobox(frame, textvariable=variable, values=values, width=max(8, width_px // 9), state="readonly").pack(
            anchor="w", ipady=3, pady=(2, 0)
        )
        return frame

    # ---------- queue and helpers ----------
    def drain_queue(self) -> None:
        try:
            while True:
                kind, payload = self.q.get_nowait()
                if kind == "log":
                    self.log(str(payload))
                elif kind == "objects":
                    self.objects = payload if isinstance(payload, dict) else None
                    self.update_object_summary()
                elif kind == "conn":
                    self.conn_var.set(str(payload))
                    self.connect_detail_var.set(str(payload))
                elif kind == "connect_state":
                    if isinstance(payload, dict):
                        self.connect_button.configure(
                            text=str(payload.get("text", "Connect")),
                            bg=str(payload.get("bg", ACCENT)),
                            fg=str(payload.get("fg", "#06111d")),
                            activebackground=str(payload.get("activebackground", "#82ccff")),
                            state=str(payload.get("state", tk.NORMAL)),
                        )
                        self.connect_detail_label.configure(fg=str(payload.get("detail_fg", INK)))
                elif kind == "dsl":
                    self.dsl_text.delete("1.0", "end")
                    self.dsl_text.insert("1.0", str(payload))
                    self.sync_name_from_dsl()
                elif kind == "source":
                    self.source_var.set(str(payload))
                elif kind == "run_state":
                    self.run_state_var.set(str(payload))
                elif kind == "status":
                    self.status_var.set(str(payload))
                elif kind == "error":
                    messagebox.showerror("Error", str(payload))
                    self.status_var.set("Error")
        except queue.Empty:
            pass
        self.after(100, self.drain_queue)

    def log(self, message: str) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.insert("end", message + "\n")
        self.log_text.see("end")
        self.log_text.configure(state=tk.DISABLED)

    def clear_log(self) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.delete("1.0", "end")
        self.log_text.configure(state=tk.DISABLED)

    def update_object_summary(self) -> None:
        if not self.objects:
            self.object_var.set("0 events / 0 RTPCs")
            return
        self.object_var.set(
            f"{len(self.objects.get('events', []))} events / {len(self.objects.get('rtpcs', []))} RTPCs"
        )

    def sync_name_from_dsl(self) -> None:
        try:
            plan = json.loads(self.dsl_text.get("1.0", "end"))
            self.run_name_var.set(f"DSL: {plan.get('name', '?')} ({len(plan.get('steps', []))} steps)")
            self.source_var.set(f"Generated by: {plan.get('_generated_by', 'manual')}")
        except Exception:  # noqa: BLE001
            self.run_name_var.set("DSL is not valid JSON")

    def on_provider_changed(self) -> None:
        provider = self.provider_var.get()
        defaults = {
            "ollama": "qwen2.5:7b-instruct",
            "openai": "gpt-5-mini",
            "anthropic": "claude-sonnet-4-5",
            "claude-cli": "claude",
            "codex-cli": "codex",
            "codex": "codex",
        }
        self.model_var.set(defaults.get(provider, ""))
        self.refresh_route_preview()

    def refresh_route_preview(self) -> None:
        try:
            label = route_label(self.cfg())
        except Exception as exc:  # noqa: BLE001
            label = f"route unavailable: {exc}"
        self.route_var.set(f"Route preview: {label}")

    def cfg(self) -> LLMConfig:
        provider = self.provider_var.get()
        model = self.model_var.get().strip()
        cfg_provider = "codex-cli" if provider == "codex" else provider
        kwargs: dict[str, object] = {"mode": self.mode_var.get(), "provider": cfg_provider}
        if provider == "ollama":
            kwargs["local_model"] = model or "qwen2.5:7b-instruct"
        elif provider == "anthropic":
            kwargs["anthropic_model"] = model or "claude-sonnet-4-5"
        elif provider == "claude-cli":
            kwargs["claude_cmd"] = model or "claude"
        elif provider in {"codex-cli", "codex"}:
            kwargs["codex_cmd"] = model or "codex"
        else:
            kwargs["openai_model"] = model or "gpt-5-mini"
        return LLMConfig(**kwargs)

    def scenario_text(self) -> str:
        return self.scenario.get("1.0", "end").strip()

    def current_plan(self) -> dict[str, object]:
        return json.loads(self.dsl_text.get("1.0", "end"))

    # ---------- actions ----------
    def do_connect(self) -> None:
        url = self.url_var.get().strip()
        self.conn_var.set("Checking...")
        self.connect_detail_var.set("Connecting WAAPI...")
        self.connect_detail_label.configure(fg=WARN)
        self.connect_button.configure(text="Connecting...", bg=WARN, fg="#06111d", state=tk.DISABLED)
        self.status_var.set("Connecting WAAPI...")
        self.log(f"\n[connect] checking {url}")

        def worker() -> None:
            try:
                engine = AudioLogicEngine(url=url, log=lambda message: self.q.put(("log", message)))
                engine.connect()
                objects = engine.fetch_objects()
                engine.disconnect()
                self.q.put(("objects", objects))
                checked = datetime.now().strftime("%H:%M:%S")
                self.q.put(("conn", f"Reachable {checked}"))
                self.q.put((
                    "connect_state",
                    {"text": "Reconnect", "bg": GOOD, "fg": "#06120f", "detail_fg": GOOD, "state": "normal"},
                ))
                self.q.put(("status", "WAAPI reachable; object list refreshed"))
                self.q.put((
                    "log",
                    f"[connect] fetched {len(objects.get('events', []))} events, "
                    f"{len(objects.get('rtpcs', []))} RTPCs, "
                    f"{len(objects.get('switch_groups', []))} switch groups.",
                ))
                self.q.put(("log", "[connect] scan connection closed; Run opens a fresh WAAPI session."))
            except Exception as exc:  # noqa: BLE001
                self.q.put(("conn", "Failed"))
                self.q.put((
                    "connect_state",
                    {"text": "Retry Connect", "bg": BAD, "fg": "#180707", "detail_fg": BAD, "state": "normal"},
                ))
                self.q.put(("log", f"[connect error] {exc}"))
                self.q.put(("error", exc))

        threading.Thread(target=worker, daemon=True).start()

    def do_generate(self) -> None:
        if not self.objects:
            messagebox.showinfo("Connect Wwise", "请先连接 / 刷新 Wwise 对象。")
            return
        scenario = self.scenario_text()
        cfg = self.cfg()
        label = route_label(cfg)
        self.status_var.set("Generating DSL...")
        self.source_var.set(f"Generating with: {label}")
        self.log(f"\n[generate] route={label}")
        self.log(f"[generate] provider={cfg.provider} model/command={self.model_var.get().strip() or '(default)'}")

        def worker() -> None:
            try:
                plan = generate_plan(scenario, self.objects or {}, cfg)
                validation = validate_plan(plan, self.objects)
                self.q.put(("dsl", json.dumps(plan, ensure_ascii=False, indent=2)))
                actual = plan.get("_generated_by", "?")
                self.q.put(("source", f"Generated by: {actual}"))
                self.q.put(("status", "DSL generated"))
                self.q.put(("log", f"[generate] done. planned={label} actual={actual}"))
                if plan.get("_generation_warning"):
                    self.q.put(("log", f"[generate] warning: {plan['_generation_warning']}"))
                self.queue_validation_log(validation)
            except Exception as exc:  # noqa: BLE001
                self.q.put(("error", exc))

        threading.Thread(target=worker, daemon=True).start()

    def queue_validation_log(self, validation: dict[str, object]) -> None:
        self.q.put((
            "log",
            f"[preflight] errors={len(validation.get('errors', []))} "
            f"warnings={len(validation.get('warnings', []))}",
        ))
        for warning in validation.get("warnings", []):
            self.q.put(("log", f"[preflight warning] {warning}"))
        for error in validation.get("errors", []):
            self.q.put(("log", f"[preflight error] {error}"))

    def do_run(self) -> None:
        if self.run_thread and self.run_thread.is_alive():
            messagebox.showinfo("Running", "已有测试正在运行，请先停止或等待结束。")
            return
        try:
            plan = self.current_plan()
        except json.JSONDecodeError as exc:
            messagebox.showerror("Invalid DSL", f"JSON 解析失败:\n{exc}")
            return
        if self.objects:
            validation = validate_plan(plan, self.objects)
            if validation["errors"]:
                self.queue_validation_log(validation)
                messagebox.showerror("Preflight Failed", "前置检查失败，请先修 DSL。")
                return
            self.queue_validation_log(validation)

        self.stop_flag.clear()
        self.clear_log()
        self.log(f"[run] starting {plan.get('name', '?')}")
        self.log(f"[run] DSL source={plan.get('_generated_by', 'manual')}")
        self.log(f"[run] WAAPI URL={self.url_var.get().strip()}")
        self.status_var.set("Running...")
        self.conn_var.set("Run connecting...")
        self.run_state_var.set("Running")
        self.run_name_var.set(f"Running: {plan.get('name', '?')}")
        url = self.url_var.get().strip()

        def worker() -> None:
            logs: list[str] = []

            def write_log(message: str) -> None:
                logs.append(str(message))
                self.q.put(("log", message))

            result: dict[str, object]
            try:
                result = run_plan(
                    plan,
                    url=url,
                    log=write_log,
                    stop_flag=self.stop_flag,
                    objects=self.objects,
                    preflight=True,
                )
                self.q.put(("conn", "Run connected OK"))
                self.q.put(("status", "Run finished"))
                self.q.put(("run_state", "PASS" if result.get("ok") else "CHECK"))
                self.q.put(("log", f"[run] result={'PASS' if result.get('ok') else 'CHECK'}"))
            except Exception as exc:  # noqa: BLE001
                result = {
                    "ok": False,
                    "error": str(exc),
                    "generated_by": plan.get("_generated_by", "manual"),
                    "log": logs,
                }
                self.q.put(("conn", "Run failed"))
                self.q.put(("status", "Run failed"))
                self.q.put(("run_state", "Failed"))
                self.q.put(("log", f"[run error] {exc}"))
                self.q.put(("error", exc))
            finally:
                try:
                    report = self.write_report(plan, result, logs)
                    self.q.put(("log", f"[report] {report}"))
                except Exception as exc:  # noqa: BLE001
                    self.q.put(("log", f"[report error] {exc}"))
                self.q.put(("source", f"Generated by: {plan.get('_generated_by', 'manual')}"))

        self.run_thread = threading.Thread(target=worker, daemon=True)
        self.run_thread.start()

    def do_stop(self) -> None:
        self.stop_flag.set()
        self.log("[stop] stop requested.")
        self.run_state_var.set("Stopping")
        self.status_var.set("Stopping...")

    def do_stamina_preset(self) -> None:
        self.scenario.delete("1.0", "end")
        self.scenario.insert("1.0", EXAMPLE)
        self.status_var.set("Loaded Stamina preset")

    # ---------- storage ----------
    def scenario_dir(self) -> Path:
        SCENARIO_DIR.mkdir(exist_ok=True)
        RAW_DIR.mkdir(exist_ok=True)
        return SCENARIO_DIR

    def refresh_library(self) -> None:
        names = sorted(path.stem for path in self.scenario_dir().glob("*.json"))
        self.lib_combo["values"] = names
        if names and not self.lib_var.get():
            self.lib_var.set(names[0])

    def do_save_raw_description(self) -> None:
        text = self.scenario_text()
        if not text:
            messagebox.showinfo("Empty", "原始描述为空。")
            return
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        first = text.splitlines()[0] if text.splitlines() else "scenario"
        path = RAW_DIR / f"{timestamp}_{safe_slug(first)}.txt"
        RAW_DIR.mkdir(exist_ok=True)
        path.write_text(text, encoding="utf-8")
        self.log(f"[save raw] {path}")
        self.status_var.set("Raw description saved")

    def do_save_bundle(self) -> None:
        path = filedialog.asksaveasfilename(defaultextension=".json", filetypes=[("JSON", "*.json")])
        if not path:
            return
        self.write_bundle(Path(path))
        self.log(f"[save bundle] {path}")

    def do_lib_save(self) -> None:
        name = simpledialog.askstring("Save To Library", "场景名称", parent=self)
        if not name:
            return
        safe = safe_slug(name)
        path = self.scenario_dir() / f"{safe}.json"
        self.write_bundle(path)
        self.refresh_library()
        self.lib_var.set(safe)
        self.log(f"[library] saved {safe}")

    def write_bundle(self, path: Path) -> None:
        dsl_raw = self.dsl_text.get("1.0", "end").strip()
        try:
            dsl_obj: object = json.loads(dsl_raw) if dsl_raw else {}
        except json.JSONDecodeError:
            dsl_obj = dsl_raw
        bundle = {
            "version": 1,
            "saved_at": datetime.now().isoformat(timespec="seconds"),
            "raw_description": self.scenario_text(),
            "scenario": self.scenario_text(),
            "dsl": dsl_obj,
            "metadata": {
                "route_preview": self.route_var.get(),
                "command_source": dsl_obj.get("_generated_by", "manual") if isinstance(dsl_obj, dict) else "manual",
                "waapi_url": self.url_var.get().strip(),
                "mode": self.mode_var.get(),
                "provider": self.provider_var.get(),
                "model_or_command": self.model_var.get().strip(),
            },
        }
        path.write_text(json.dumps(bundle, ensure_ascii=False, indent=2), encoding="utf-8")

    def do_lib_load(self) -> None:
        name = self.lib_var.get().strip()
        if not name:
            return
        self.load_bundle(self.scenario_dir() / f"{name}.json")

    def do_load(self) -> None:
        path = filedialog.askopenfilename(filetypes=[("Audio Logic", "*.json;*.txt"), ("JSON", "*.json"), ("Text", "*.txt")])
        if not path:
            return
        selected = Path(path)
        if selected.suffix.lower() == ".txt":
            self.scenario.delete("1.0", "end")
            self.scenario.insert("1.0", selected.read_text(encoding="utf-8"))
            self.log(f"[load raw] {selected}")
            return
        self.load_bundle(selected)

    def load_bundle(self, path: Path) -> None:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            messagebox.showerror("Load Failed", str(exc))
            return
        if isinstance(data, dict) and "steps" in data:
            raw_description = data.get("_raw_description", "")
            dsl = data
        elif isinstance(data, dict):
            raw_description = data.get("raw_description", data.get("scenario", ""))
            dsl = data.get("dsl", {})
        else:
            messagebox.showerror("Load Failed", "无法识别的文件格式。")
            return
        self.scenario.delete("1.0", "end")
        self.scenario.insert("1.0", raw_description)
        self.dsl_text.delete("1.0", "end")
        if isinstance(dsl, (dict, list)):
            self.dsl_text.insert("1.0", json.dumps(dsl, ensure_ascii=False, indent=2))
        else:
            self.dsl_text.insert("1.0", str(dsl))
        self.sync_name_from_dsl()
        self.log(f"[load] {path}")

    def write_report(self, plan: dict[str, object], result: dict[str, object], logs: list[str]) -> Path:
        REPORT_DIR.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        name = safe_slug(str(plan.get("name", "AudioLogicTest")))
        path = REPORT_DIR / f"ProjectEF_AudioLogicTester_{name}_{timestamp}.md"
        validation = result.get("validation") if isinstance(result.get("validation"), dict) else {}
        posted = result.get("posted_events", []) if isinstance(result.get("posted_events"), list) else []
        lines = [
            "# ProjectEF Audio Logic Tester Report",
            "",
            f"- Result: {'PASS' if result.get('ok') else 'CHECK / FAILED'}",
            f"- Scenario: {plan.get('name', '?')}",
            f"- Command source: {plan.get('_generated_by', result.get('generated_by', 'manual'))}",
            f"- Generated at: {plan.get('_generated_at', '')}",
            f"- Report time: {datetime.now().isoformat(timespec='seconds')}",
            "",
            "## Original Description",
            "",
            "```text",
            str(plan.get("_raw_description", self.scenario_text())),
            "```",
            "",
            "## Preflight",
            "",
            f"- Errors: {len(validation.get('errors', [])) if validation else 0}",
            f"- Warnings: {len(validation.get('warnings', [])) if validation else 0}",
        ]
        for warning in validation.get("warnings", []) if validation else []:
            lines.append(f"- Warning: {warning}")
        for error in validation.get("errors", []) if validation else []:
            lines.append(f"- Error: {error}")
        if result.get("error"):
            lines.extend(["", "## Error", "", f"```text\n{result['error']}\n```"])
        lines.extend(["", "## Posted Events", ""])
        if posted:
            lines.extend(["| Event | Playing ID |", "| --- | --- |"])
            for item in posted:
                if isinstance(item, dict):
                    lines.append(f"| {item.get('event')} | {item.get('playing_id')} |")
        else:
            lines.append("No posted events recorded.")
        lines.extend(["", "## Run Log", "", "```text"])
        lines.extend(logs or [str(item) for item in result.get("log", [])] if isinstance(result.get("log"), list) else [])
        lines.append("```")
        path.write_text("\n".join(lines), encoding="utf-8")
        return path


def safe_slug(value: str) -> str:
    slug = re.sub(r'[\\/:*?"<>|\s]+', "_", value.strip())[:64].strip("_")
    return slug or "scenario"


def main() -> None:
    AudioLogicTesterGUI().mainloop()


if __name__ == "__main__":
    main()
